// 路由常量，映射自 src/core/router/index.ts
export class RouteConst {
  static readonly HOME = 'Home'
  static readonly MUSIC_DETAIL = 'MusicDetail'
  static readonly SEARCH = 'Search'
  static readonly SETTING = 'Setting'
  static readonly TOP_LIST = 'TopList'
  static readonly TOP_LIST_DETAIL = 'TopListDetail'
  static readonly ALBUM_DETAIL = 'AlbumDetail'
  static readonly ARTIST_DETAIL = 'ArtistDetail'
  static readonly LOCAL_SHEET_DETAIL = 'LocalSheetDetail'
  static readonly PLUGIN_SHEET_DETAIL = 'PluginSheetDetail'
  static readonly LOCAL_MUSIC = 'LocalMusic'
  static readonly DOWNLOADING = 'Downloading'
  static readonly HISTORY = 'History'
  static readonly RECOMMEND_SHEETS = 'RecommendSheets'
}
